import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  const agents = [
    {
      slug: "career7-english-teacher",
      name: "English Teacher",
      tagline: "Speak clearer every week.",
      description: "Daily spoken English practice, grammar cleanup, and confidence drills for Career7 learners.",
      category: "EDUCATION",
      type: "UI",
      career7Type: "LEARNING",
      creditPrice: 100,
      career7Status: "ACTIVE",
      canAddToGrowthBoard: true,
      isPrebuilt: true,
      isRequestable: true,
      icon: "EN",
      colorPrimary: "#7C3AED",
      colorSecondary: "#22D3EE",
      gradient: "linear-gradient(135deg,#2e1065,#083344)",
      onboardingFee: 0,
      monthlyFee: 0,
      sortOrder: 101,
      features: ["Speaking drills", "Grammar practice", "Pronunciation coaching", "Daily confidence tasks"]
    },
    {
      slug: "career7-resume-builder",
      name: "Resume Builder",
      tagline: "Turn experience into interviews.",
      description: "Create sharper, ATS-friendly resumes with stronger summaries, bullets, and job keywords.",
      category: "EDUCATION",
      type: "UI",
      career7Type: "CAREER",
      creditPrice: 80,
      career7Status: "ACTIVE",
      canAddToGrowthBoard: true,
      isPrebuilt: true,
      isRequestable: true,
      icon: "CV",
      colorPrimary: "#2563EB",
      colorSecondary: "#06B6D4",
      gradient: "linear-gradient(135deg,#1e3a8a,#0e7490)",
      onboardingFee: 0,
      monthlyFee: 0,
      sortOrder: 102,
      features: ["ATS keywords", "Bullet rewriting", "Profile summary", "Role matching"]
    },
    {
      slug: "career7-job-matcher",
      name: "Job Matcher",
      tagline: "Find roles that fit.",
      description: "Match skills and goals to realistic opportunities, then build a focused application list.",
      category: "UNIVERSAL",
      type: "UI",
      career7Type: "EARNING",
      creditPrice: 100,
      career7Status: "ACTIVE",
      canAddToGrowthBoard: true,
      isPrebuilt: true,
      isRequestable: true,
      icon: "JOB",
      colorPrimary: "#059669",
      colorSecondary: "#14B8A6",
      gradient: "linear-gradient(135deg,#064e3b,#115e59)",
      onboardingFee: 0,
      monthlyFee: 0,
      sortOrder: 103,
      features: ["Opportunity matching", "Application shortlist", "Skill gap hints", "Job tracking"]
    },
    {
      slug: "career7-interview-coach",
      name: "Interview Coach",
      tagline: "Practice before it matters.",
      description: "Prepare concise interview answers, improve confidence, and rehearse common role questions.",
      category: "EDUCATION",
      type: "UI",
      career7Type: "CAREER",
      creditPrice: 100,
      career7Status: "ACTIVE",
      canAddToGrowthBoard: true,
      isPrebuilt: true,
      isRequestable: true,
      icon: "INT",
      colorPrimary: "#DB2777",
      colorSecondary: "#F97316",
      gradient: "linear-gradient(135deg,#831843,#9a3412)",
      onboardingFee: 0,
      monthlyFee: 0,
      sortOrder: 104,
      features: ["Mock questions", "Answer structure", "Confidence drills", "Feedback prompts"]
    },
    {
      slug: "sales-booster",
      name: "Sales Booster",
      tagline: "Every lead. One dashboard.",
      description: "WhatsApp, Instagram, Facebook, Email, and SMS - all managed by NEXA in one place. Never miss a lead from any channel again.",
      category: "UNIVERSAL",
      type: "BACKGROUND",
      icon: "⚡",
      colorPrimary: "#7C6FFF",
      colorSecondary: "#22D9A0",
      gradient: "linear-gradient(135deg,#0d0820,#050d15)",
      onboardingFee: 5999,
      monthlyFee: 1499,
      isFeatured: true,
      sortOrder: 1,
      features: ["WhatsApp Business API", "Instagram DM automation", "Facebook lead forms", "Email inbox aggregation", "SMS campaigns", "NEXA lead scoring", "Outbound campaign manager", "Source analytics", "Auto-reply templates", "One CRM pipeline"],
      benefits: [
        { icon: "🚫", title: "Zero missed leads", desc: "Every enquiry from every platform captured automatically." },
        { icon: "⏰", title: "Instant response", desc: "NEXA auto-replies within seconds. Leads get acknowledged immediately." },
        { icon: "📈", title: "Source analytics", desc: "Know which channel brings your best leads. Spend smarter on ads." },
        { icon: "🤖", title: "NEXA manages campaigns", desc: "Broadcast on WhatsApp, run Instagram DM campaigns, send email sequences." },
        { icon: "🔗", title: "One pipeline", desc: "All leads flow into your BGOS CRM regardless of source." },
        { icon: "🛠️", title: "Set up by our team", desc: "Our SDE team handles all API connections. Ready in 24 hours." }
      ],
      howItWorks: [
        { step: "01", icon: "🔌", title: "We connect your channels", desc: "Our SDE team connects WhatsApp Business, Instagram, Facebook, email, and SMS. All authorised and tested." },
        { step: "02", icon: "⚡", title: "NEXA aggregates all leads", desc: "Every enquiry from every channel flows into your Sales Booster dashboard automatically." },
        { step: "03", icon: "🎯", title: "NEXA scores and assigns", desc: "NEXA scores every lead by quality, assigns them to your team, and sends follow-up reminders." },
        { step: "04", icon: "📊", title: "Track everything", desc: "See which channel brings the best leads, response times, and conversion by source." }
      ]
    },
    {
      slug: "wazzup",
      name: "Wazzup",
      tagline: "Run your business on WhatsApp.",
      description: "NEXA lives in your WhatsApp. Manage your team, track leads, get daily briefings, and approve tasks - all without opening a laptop.",
      category: "UNIVERSAL",
      type: "BACKGROUND",
      icon: "💬",
      colorPrimary: "#25D366",
      colorSecondary: "#128C7E",
      gradient: "linear-gradient(135deg,#0d1a0f,#050a08)",
      onboardingFee: 3999,
      monthlyFee: 999,
      isFeatured: false,
      sortOrder: 2,
      features: ["NEXA on WhatsApp 24/7", "Daily morning briefing", "Lead updates and alerts", "Task approval over WhatsApp", "Team performance updates", "Send follow-ups by asking NEXA", "Health score updates", "Instant escalation alerts"]
    },
    {
      slug: "taxmate",
      name: "TaxMate",
      tagline: "Taxes, invoices, and payments - all on autopilot.",
      description: "Every business compliance requirement automated and never missed. TaxMate handles Tax filing reminders, withholding tax alerts, invoice generation, and payment tracking.",
      category: "FINANCE",
      type: "BACKGROUND",
      icon: "🧾",
      colorPrimary: "#F5A623",
      colorSecondary: "#22D9A0",
      gradient: "linear-gradient(135deg,#1a1205,#120f00)",
      onboardingFee: 1999,
      monthlyFee: 799,
      sortOrder: 3,
      features: ["Tax filing reminders", "withholding tax alerts", "Automated invoice generation", "Payment tracking", "Outstanding follow-ups", "business compliance", "accounting integration", "Monthly tax summary"]
    },
    {
      slug: "peopledesk",
      name: "PeopleDesk",
      tagline: "Your HR department - automated.",
      description: "Attendance tracking, leave management, payroll reminders, employee onboarding, and performance reviews - all handled by NEXA.",
      category: "UNIVERSAL",
      type: "BACKGROUND",
      icon: "👥",
      colorPrimary: "#7C6FFF",
      colorSecondary: "#FF6B6B",
      gradient: "linear-gradient(135deg,#0a0a1a,#120a1a)",
      onboardingFee: 3999,
      monthlyFee: 799,
      sortOrder: 4,
      features: ["Attendance tracking", "Leave management", "Payroll reminders", "Employee onboarding", "Performance reviews", "Offer letter generation", "Holiday calendar", "HR reports"]
    },
    {
      slug: "sitesync",
      name: "SiteSync",
      tagline: "From blueprint to handover.",
      description: "Built for builders, construction companies, and solar installers. Drawing management, site visits, contractor coordination, and project milestone tracking.",
      category: "CONSTRUCTION",
      type: "BACKGROUND",
      icon: "🏗️",
      colorPrimary: "#4CAF50",
      colorSecondary: "#8BC34A",
      gradient: "linear-gradient(135deg,#0f1a00,#1a1200)",
      onboardingFee: 5999,
      monthlyFee: 1499,
      sortOrder: 5,
      features: ["Drawing management", "Site visit scheduling", "Contractor coordination", "Approval workflows", "Material tracking", "Project milestones", "Delay alerts", "Client updates"]
    },
    {
      slug: "careloop",
      name: "CareLoop",
      tagline: "Patients never fall through the cracks.",
      description: "For clinics and hospitals. Appointment reminders via WhatsApp and SMS, prescription follow-ups, lab report tracking, and patient satisfaction automation.",
      category: "HEALTHCARE",
      type: "BACKGROUND",
      icon: "🏥",
      colorPrimary: "#00BCD4",
      colorSecondary: "#2196F3",
      gradient: "linear-gradient(135deg,#0a1520,#00101a)",
      onboardingFee: 4999,
      monthlyFee: 1299,
      sortOrder: 6,
      features: ["Appointment reminders", "Prescription follow-ups", "Lab report tracking", "Patient satisfaction surveys", "Doctor availability", "Billing alerts", "Patient history", "Referral tracking"]
    },
    {
      slug: "eduflow",
      name: "EduFlow",
      tagline: "Every student journey tracked.",
      description: "For coaching academies and training centres. Student progress, batch management, fee collection automation, parent communication, and exam scheduling.",
      category: "EDUCATION",
      type: "BACKGROUND",
      icon: "🎓",
      colorPrimary: "#FF9800",
      colorSecondary: "#FF5722",
      gradient: "linear-gradient(135deg,#1a0f00,#1a0a00)",
      onboardingFee: 3999,
      monthlyFee: 999,
      sortOrder: 7,
      features: ["Student progress tracking", "Batch management", "Fee collection automation", "Parent communication", "Exam scheduling", "Attendance alerts", "Performance reports", "Admission pipeline"]
    },
    {
      slug: "classmate",
      name: "ClassMate",
      tagline: "Teachers teach. ClassMate handles the rest.",
      description: "For schools. Lesson plan management, student attendance, homework tracking, parent communication portal, PTM scheduling, and report card generation.",
      category: "EDUCATION",
      type: "BACKGROUND",
      icon: "🏫",
      colorPrimary: "#9C27B0",
      colorSecondary: "#673AB7",
      gradient: "linear-gradient(135deg,#150a1a,#0f0a20)",
      onboardingFee: 4999,
      monthlyFee: 1299,
      sortOrder: 8,
      features: ["Lesson plan management", "Student attendance", "Homework tracking", "Parent communication portal", "PTM scheduling", "Report card generation", "Teacher workload", "School announcements"]
    },
    {
      slug: "proppilot",
      name: "PropPilot",
      tagline: "Close more properties.",
      description: "For real estate agencies. Site visit scheduling, broker network management, property matching for leads, token and agreement tracking, and referral management.",
      category: "REAL_ESTATE",
      type: "BACKGROUND",
      icon: "🏢",
      colorPrimary: "#009688",
      colorSecondary: "#4CAF50",
      gradient: "linear-gradient(135deg,#001a0f,#001510)",
      onboardingFee: 3999,
      monthlyFee: 1299,
      sortOrder: 9,
      features: ["Site visit scheduling", "Broker network management", "Property matching", "Token tracking", "Agreement alerts", "Post-sale follow-up", "Referral management", "Commission tracking"]
    },
    {
      slug: "stocksense",
      name: "StockSense",
      tagline: "Orders, dealers, payments - all flowing.",
      description: "For retail and distribution businesses. Dealer network management, order tracking, dispatch alerts, payment follow-ups, and reorder reminders.",
      category: "RETAIL",
      type: "BACKGROUND",
      icon: "🏪",
      colorPrimary: "#FF5722",
      colorSecondary: "#FF9800",
      gradient: "linear-gradient(135deg,#1a0a05,#1a0500)",
      onboardingFee: 3999,
      monthlyFee: 999,
      sortOrder: 10,
      features: ["Dealer network management", "Order tracking", "Dispatch alerts", "Payment follow-ups", "Reorder reminders", "Sales rep performance", "Distributor communication", "Inventory alerts"]
    }
  ]

  for (const agent of agents) {
    await prisma.marketplaceAgent.upsert({
      where: { slug: agent.slug },
      create: agent as any,
      update: agent as any
    })
  }

  const blizzwayCompanions = [
    ["bdp-builder-companion", "BDP Builder Companion", "BDP & Profile", "CAREER", 0, "free", "BDP", true],
    ["resume-architect-companion", "Resume Architect Companion", "BDP & Profile", "CAREER", 120, "credits", "CV", true],
    ["linkedin-profile-companion", "LinkedIn Profile Companion", "BDP & Profile", "CAREER", 90, "credits", "IN", false],
    ["portfolio-builder-companion", "Portfolio Builder Companion", "BDP & Profile", "CAREER", 140, "credits", "PF", false],
    ["career-compass-companion", "Career Compass Companion", "Career Growth", "CAREER", 0, "free", "CC", true],
    ["english-speaking-companion", "English Speaking Companion", "Language & Communication", "LANGUAGE", 80, "credits", "EN", true],
    ["ielts-companion", "IELTS Companion", "Exam Coaching", "EXAM", 180, "credits", "IE", false],
    ["german-companion", "German Companion", "Language & Communication", "LANGUAGE", 130, "credits", "DE", false],
    ["communication-coach-companion", "Communication Coach", "Language & Communication", "LANGUAGE", 70, "credits", "COM", false],
    ["interview-companion", "Interview Companion", "Career Growth", "CAREER", 110, "credits", "INT", false],
    ["sop-lor-companion", "SOP/LOR Companion", "Admissions", "MIGRATION", 160, "credits", "SOP", false],
    ["college-admission-companion", "College Admission Companion", "Admissions", "MIGRATION", 150, "credits", "ADM", false],
    ["scholarship-companion", "Scholarship Companion", "Admissions", "MIGRATION", 170, "credits", "SCH", false],
    ["visa-readiness-companion", "Visa Readiness Companion", "Migration & Global Mobility", "MIGRATION", 190, "credits", "VISA", false],
    ["freelance-finder-companion", "Freelance Finder Companion", "Earning Universe", "EARNING", 100, "credits", "FF", true],
    ["job-match-companion", "Job Match Companion", "Earning Universe", "EARNING", 120, "credits", "JOB", false],
    ["money-discipline-companion", "Money Discipline Companion", "Finance & Money Discipline", "FINANCE", 0, "free", "INR", false],
    ["confidence-companion", "Confidence Companion", "Happiness & Personal Growth", "LEARNING", 60, "credits", "YOU", false],
    ["focus-companion", "Focus Companion", "Happiness & Personal Growth", "LEARNING", 50, "credits", "FOC", false],
    ["guardian-angel-pathway-companion", "Guardian Angel Pathway Companion", "Blizzway Premium", "BLIZZWAY", 300, "premium", "NEXA", true],
  ]

  for (let index = 0; index < blizzwayCompanions.length; index += 1) {
    const [slug, name, companionCategory, career7Type, creditPrice, pricingMode, icon, featured] = blizzwayCompanions[index]
    const description = `${name} helps Blizzway users complete focused pathway actions across ${companionCategory}.`
    const chargeOn = slug === "resume-architect-companion" ? "activation" : "run"

    await prisma.marketplaceAgent.upsert({
      where: { slug: slug as string },
      create: {
        slug,
        name,
        tagline: description,
        description,
        shortDescription: description,
        longDescription: `${description} This v1 companion uses safe rule-based execution and prepares a clean path for future LLM orchestration.`,
        category: companionCategory === "Finance & Money Discipline" ? "FINANCE" : "EDUCATION",
        type: "UI",
        career7Type,
        companionCategory,
        creditPrice,
        pricingMode,
        career7Status: "ACTIVE",
        businessModel: "blizzway",
        icon,
        colorPrimary: "#4F46E5",
        colorSecondary: "#06B6D4",
        gradient: "linear-gradient(135deg,#312e81,#0e7490)",
        onboardingFee: 0,
        monthlyFee: 0,
        isFeatured: Boolean(featured),
        isTrending: index < 8,
        isPrebuilt: true,
        isRequestable: true,
        canAddToGrowthBoard: true,
        sortOrder: 200 + index,
        capabilities: ["Guided intake", "Rule-based action plan", "Pathway-ready checklist"],
        expectedOutput: ["Summary", "Checklist", "Next actions", "Safety note"],
        recommendedFor: ["Blizzway users", companionCategory],
        requiredInputs: ["Goal", "Current status", "Main blocker"],
        chargeOn,
        features: ["Safe v1 execution", "Structured output", "Future LLM-ready architecture"],
      } as any,
      update: {
        name,
        tagline: description,
        description,
        shortDescription: description,
        longDescription: `${description} This v1 companion uses safe rule-based execution and prepares a clean path for future LLM orchestration.`,
        category: companionCategory === "Finance & Money Discipline" ? "FINANCE" : "EDUCATION",
        type: "UI",
        career7Type,
        companionCategory,
        creditPrice,
        pricingMode,
        career7Status: "ACTIVE",
        businessModel: "blizzway",
        icon,
        isFeatured: Boolean(featured),
        isTrending: index < 8,
        isPrebuilt: true,
        isRequestable: true,
        canAddToGrowthBoard: true,
        sortOrder: 200 + index,
        capabilities: ["Guided intake", "Rule-based action plan", "Pathway-ready checklist"],
        expectedOutput: ["Summary", "Checklist", "Next actions", "Safety note"],
        recommendedFor: ["Blizzway users", companionCategory],
        requiredInputs: ["Goal", "Current status", "Main blocker"],
        chargeOn,
        features: ["Safe v1 execution", "Structured output", "Future LLM-ready architecture"],
      } as any,
    })
  }

  console.log("Marketplace agents seeded successfully")
}

main().catch(console.error).finally(() => prisma.$disconnect())
